### ISSUE TITLE
Outdated Chrome manifest

### ISSUE THREAD

**Issue by kramrm** [joshhunt/season-pass-extension#1]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

**Comment by joshhunt** [comment]
Yup. At that point, this extension will just not be available on Chrome. Last time I checked manifest v3 lacks features that this extension needs.

**Comment by Prometheus3375** [comment]
I've been using this extensions even with outdated manifest this year. Noticed that manifest is obsolete only today. Can you check again of it is can be updated?
