### ISSUE TITLE
The season pass is empty

### ISSUE THREAD

**Issue by Elbenny19** [joshhunt/season-pass-extension#11]
Hello , the season pass has nothing in it , like no image no nothing that i can click on , only things that shows is the tier of the season and the squares where an item would be either the paid or the free version and the color diference between levels i reached and the ones i didnt  , its like an empty excel sheet with the respective  tier number on top , i tried on any season , on the season of the hunt where i reached tier 97 happends the same , only last season season of the deep shows the respective items, sorry for the lengthy text tho

Edit : so it only works for the season of the risen and the seasons after  , wich is a shame since i last time i played was season of the hunt , the one before

**Comment by joshhunt** [comment]
Correct. 

> Over time very old seasons become unavailable in the Destiny API - only season's that have rewards to be pulled are visible in the API. Each Destiny 2 season carries a risk of Bungie removing older seasons, so do not leave rewards unobtained that you would be upset if you lost.

**Comment by Elbenny19** [comment]
Damn what a shame they wiped the old seasons i just came back to destiny since beyond ligth and yea was worth a try as i never used hunter or titan and it would give me a boost in materials... thougth it was a bug or even a fuck up from my end but yea just unfortunate timing, thank you for clearing my doubts/problem
