### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by bel57** [joshhunt/season-pass-extension#2]
Hello there,
Not a top priority.. Is it also possible to add the translation for (non English) officially supported languages?
Can you extract them from bnet/read user locale, maybe?
Thanks for this addon, looking forward to its release on the Chrome web store :)

**Comment by joshhunt** [comment]
Sorry, but it just won't be translated.

**Comment by Gerar2k** [comment]
Hi, I translated it to spanish, could you send me the background.bundle.js uncompressed?
